### ISSUE TITLE
Provide historical cheatsheets

### ISSUE THREAD

**Issue by schveiguy** [raysan5/raylib.com#27]
I'm not ready to switch to raylib 4.0, I'm on raylib 3.7.0. But the cheatsheet has been updated, and there doesn't seem to be a PDF version of that one.

Not only that, but the older pdfs have no links on the site.

It would be nice to just have a way to select which version of the cheatsheet you want to see. Should be as easy as copying the older cheatsheet directories to a subdirectory for the main website.

Yes, I know I can look at the headers, but the cheatsheet is easy to use.

**Comment by icodealot** [comment]
@schveiguy I don't know if you are still missing the 3.7 cheatsheet but as a workaround in the meantime, you can clone the raylib.com website source from here and checkout the older commits before it was updated to 4.0, or possibly grab what you need from [web archive](http://web.archive.org/web/20210512191150/https://www.raylib.com/cheatsheet/cheatsheet.html) and roll your own PDF using Chrome -> Print -> Save as PDF, etc. (This creates a multi-page PDF instead of the single-page PDF like the raylib.com but hopefully better than nothing?) 

Cheers.

**Comment by schveiguy** [comment]
I have since gone to 4.0. But thanks for the tips! This issue report isn't really an ask for someone to solve this specific problem for me, I actually had already built the appropriate cheatsheet for myself by recreating the process.

It's more of a suggestion because it's trivial to do and adds some value for those who need it.
